name: "gh-deploy-sheet-updater"
description: "Github Action 배포시트 업데이트"
author: "deali-web"

inputs:
  project:
    description: "프로젝트명"
    required: true
  environment:
    description: "실행환경"
    required: true
  commit_message:
    description: "마지막 커밋 메시지"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run script
      run: node ${{ github.action_path }}/target/index.js
      shell: bash
