name: "gh-deploy-sheet-updater"
description: "Github Action 배포시트 업데이트"
author: "deali-web"

inputs:
  project:
    description: "프로젝트명"
    required: true
  environment:
    description: "실행환경"
    required: true
  message:
    description: "배포 용도"
    required: true
  end_date:
    description: "사용기간"
    required: true
  github_ref_name:
    description: "Github Ref Name"
    required: false
  github_actor:
    description: "Github Actor"
    required: false
  google_sheets_credentials:
    description: "Google Sheets Credentials"
    required: true
  spreadsheet_id:
    description: "Google Sheets Spreadsheet ID"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
