name: "gh-deploy-sheet-updater"
description: "Github Action 배포시트 업데이트"
author: "deali-web"

inputs:
  project:
    description: "프로젝트명"
    required: true
  environment:
    description: "실행환경"
    required: true
  message:
    description: "배포 용도"
    required: false
  end_date:
    description: "사용기간"
    required: false
  github_ref_name:
    description: "Github Ref Name"
    required: false
  github_actor:
    description: "Github Actor"
    required: false
  commit_message:
    description: "커밋 메시지 (예: github.event.head_commit.message)"
    required: false
  pr_number:
    description: "PR 번호 (예: github.event.pull_request.number)"
    required: false
  pr_title:
    description: "PR 제목 (예: github.event.pull_request.title)"
    required: false
  google_sheets_credentials:
    description: "Google Sheets Credentials"
    required: true
  spreadsheet_id:
    description: "Google Sheets Spreadsheet ID"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
