name: "gh-deploy-sheet-updater"
description: "Github Action 배포시트 업데이트"
author: "deali-web"

inputs:
  project:
    description: "프로젝트명"
    required: true
  environment:
    description: "실행환경"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Install dependencies
      run: yarn install --production --frozen-lockfile
      shell: bash

    - name: Run script
      run: yarn node target/index.js
      shell: bash
